version: "3.7"

services:
  
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27018:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data-mongo-volume:/data/db
    networks:
      - devnet
  
networks:
  devnet:
    driver: bridge
    name: devnet_network

